name: Verify
on: [push]
jobs:
  Verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - run: yarn install
      - run: yarn copy-aws-exports
      - run: yarn lint
      - run: yarn type-check
      - run: yarn test
